org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.configuration-cache=false
systemProp.java.net.preferIPv4Stack=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

iktaun_model_loader_version=1.0.0
iktaun_gui_loader_version=1.0.0

the_new_developing_age_version=0.1.0
contemporary_construction_version=0.2.0
peace_and_war_version=0.1.0
contemporary_agriculture_version=0.1.0
cyberpunk_world_version=0.1.0

jei_version=15.20.0.129
mixinextras_version=0.4.1

maven_group=com.iktaun